services:
  # Production Services
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  web-stage:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000" # Use a different port
    environment:
      - NODE_ENV=test
    depends_on:
      - db-stage
    networks:
      - network_stage

  db-stage:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_DEVELOPMENT}
    ports:
      - "5433:5432" # Use a different port
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data
    networks:
      - network_stage

  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000" # Use a different port
    environment:
      - NODE_ENV=development
    volumes:
      - .:/src
    depends_on:
      - db-dev
    networks:
      - network_dev

  db-dev:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_DEVELOPMENT}
    ports:
      - "5434:5432" # Unique port for development
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - network_dev

volumes:
  postgres_data:
  postgres_data_stage:
  postgres_data_dev:

networks:
  network:
    driver: bridge
  network_stage:
    driver: bridge
  network_dev:
    driver: bridge
