version: "3.8"

services:
  # Testing Services
  web-development:
    build: .
    ports:
      - "3001:3000" # Use a different port
    environment:
      - NODE_ENV=development
    depends_on:
      - db-development
    networks:
      - my_network_development

  db-development:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_DEVELOPMENT}
    ports:
      - "5433:5432" # Use a different port
    volumes:
      - postgres_data_development:/var/lib/postgresql/data
    networks:
      - my_network_development

volumes:
  postgres_data_development:

networks:
  my_network_development:
    driver: bridge
